# Site settings
title: De Geist
email: hello@degeist.com
description: > # this means to ignore newlines until "baseurl:"
  We think about and create Internet things. We can help you make the most out of the networked world.
twitter_description: In ut quam vitae odio lacinia tincidunt. Pellentesque posuere
baseurl: /page # in development. For Github  ""
url: "http://degeist.com/" # the base hostname & protocol for your site
name: De Geist
twitter_username: degeist
facebook_username: facebook

# Build settings
markdown: redcarpet
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
